export const CHANGE_HOME_DATA = 'home/CHANGE_HOME_DATA';
export const ADD_RECOMMEND_ARTICLE_WITH_PROFILE ='home/ADD_RECOMMEND_ARTICLE_WITH_PROFILE';
export const TOGGLE_SCROLL_TOP ='home/TOGGLE_SCROLL_TOP';
export const SET_WRITER_LIST ='home/SET_WRITER_LIST';
export const CHANGE_FOLLOWED_LIST ='home/CHANGE_FOLLOWED_LIST';
export const CHANGE_RECOMMEND_ARTICLE_WITH_PROFILE ='home/CHANGE_RECOMMEND_ARTICLE_WITH_PROFILE';

