export const CHANGE_LOGIN = 'login/CHANGE_LOGIN';
export const LOGOUT = 'login/LOGOUT';
export const CHANGE_REGISTER = 'login/CHANGE_REGISTER';
export const CHANGE_REGISTER_USERNAME = 'login/CHANGE_REGISTER_USERNAME';
export const CHANGE_REGISTER_PASSWORD = 'login/CHANGE_REGISTER_PASSWORD';
export const CHANGE_REGISTER_RE_PASSWORD = 'login/CHANGE_REGISTER_RE_PASSWORD';
export const SET_USER_INFO = 'login/SET_USER_INFO';